# Generated by Django 3.2.3 on 2021-06-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('emailid', models.EmailField(max_length=20)),
                ('mobile', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
