# Generated by Django 3.2.3 on 2021-06-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='doc_pic'),
        ),
    ]
