# Generated by Django 3.2.3 on 2021-06-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='patient_pic'),
        ),
    ]
